(#605) Unbreak bolt_task with multiple files
choria-io/mcollective-choria pull request #642
Opened 2020-12-23 23:56 UTC by smortex

Allow running a Bolt task that use extra files beside the task script itself.

2020-12-24 01:39 UTC, smortex commented
Ping @jay7x!  This is a follow-up to #605

Using this patch, I can run [a Bolt tasks](https://github.com/opus-codium/puppet-odoo/blob/master/tasks/databases_list.sh) that needs [an extra file](https://github.com/opus-codium/puppet-odoo/blob/master/files/databases-list.py).

I do not use much more than this for now, so if you can test how it behave in your use case and report feedback here, it would be awesome!

2020-12-24 01:51 UTC, smortex commented
For the record, in order to test, I stop puppet and overwrite the files in `/opt/puppetlabs/mcollective/plugins/mcollective/` with the ones from this repository.  When I am done, I restart puppet which restores the original files.

2020-12-24 05:35 UTC, ripienaar requested changes

2020-12-24 05:35 UTC, ripienaar commented on spec/unit/mcollective/util/tasks_support_spec.rb
> +          FileUtils.stubs(:cp).with(File.join(cache, "f3b4821836cf7fe6fe17dfb2924ff6897eba43a44cc4cba0e0ed136b27934ede"), File.join(spooldir, "files", "ls.rb"))
better make these `expects` I think, then it actually checks the calls are done

2020-12-24 05:36 UTC, ripienaar commented on spec/unit/mcollective/util/tasks_support_spec.rb
> +          FileUtils.stubs(:cp).with(File.join(cache, "f3b4821836cf7fe6fe17dfb2924ff6897eba43a44cc4cba0e0ed136b27934ede"), File.join(spooldir, "files", "ls.rb"))
looks amazing thank you, just that one thing

2020-12-24 19:21 UTC, smortex commented on spec/unit/mcollective/util/tasks_support_spec.rb
> +          FileUtils.stubs(:cp).with(File.join(cache, "f3b4821836cf7fe6fe17dfb2924ff6897eba43a44cc4cba0e0ed136b27934ede"), File.join(spooldir, "files", "ls.rb"))
Good catch, thanks!

2020-12-25 15:33 UTC, ripienaar commented
looks good to me

2020-12-25 15:33 UTC, ripienaar approved these changes

2020-12-25 15:33 UTC, ripienaar commented
you all ready with this? I'll go ahead and merge then

2020-12-25 16:50 UTC, smortex commented
That looks ok for me, my end-to-end testing is currently limited by #439 which I started to work on at $WORK (but and authentication failure by the database is exactly what I would expect from my code running as the wrong user).

The only "inconsistency" I see when comparing with Bolt is that the task script is in `<spooldir>/script` while with Bolt it's in `<tempdir>/<modulename>/tasks/script`.  But I do not think this is a problem since it's the "entry point" and nothing should refer to this file.

2020-12-26 13:04 UTC, merged